# Generated by Django 4.2.13 on 2024-06-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0006_presence_pickup_name"),
        ("reports", "0002_rename_reports_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="guests",
            field=models.ManyToManyField(related_name="reports", to="guests.guest"),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_text",
            field=models.TextField(max_length=200),
        ),
        migrations.CreateModel(
            name="MentionedGuest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="guests.guest"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reports.report"
                    ),
                ),
            ],
            options={
                "ordering": ["report_id"],
            },
        ),
    ]
