# Generated by Django 4.2.13 on 2024-06-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0006_presence_pickup_name"),
        ("reports", "0003_report_guests_alter_report_report_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="guests",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="reports", to="guests.guest"
            ),
        ),
    ]
