# Generated by Django 4.2.13 on 2024-06-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_alter_report_guests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_text",
            field=models.TextField(max_length=300),
        ),
    ]
