# Generated by Django 4.2.13 on 2024-07-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0007_remove_presence_pickup"),
        ("reports", "0005_alter_report_report_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mentionedguest",
            options={"ordering": ["report"]},
        ),
        migrations.AlterField(
            model_name="report",
            name="guests",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="guests.guest"
            ),
        ),
    ]
