# Generated by Django 4.2.13 on 2024-07-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_alter_mentionedguest_options_alter_report_guests"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MentionedGuest",
        ),
    ]
