# Generated by Django 4.2.11 on 2024-04-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("information", models.TextField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("name_addon", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(0, "Male"), (1, "Female"), (2, "Other")], default=0
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("information", models.TextField(blank=True, null=True)),
                ("picture_url", models.URLField(blank=True, null=True)),
                ("food", models.BooleanField(default=False)),
                ("food_time_1", models.TimeField(blank=True, null=True)),
                ("food_time_2", models.TimeField(blank=True, null=True)),
                ("food_time_3", models.TimeField(blank=True, null=True)),
                ("medication", models.BooleanField(default=False)),
                ("medication_time_1", models.TimeField(blank=True, null=True)),
                ("medication_time_2", models.TimeField(blank=True, null=True)),
                ("medication_time_3", models.TimeField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guests.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["first_name"],
            },
        ),
    ]
