# Generated by Django 4.2.11 on 2024-06-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0005_presence_pickup_presence_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="presence",
            name="pickup_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
